@startuml
!include style.puml

skinparam ArrowFontStyle plain

actor User
participant ":CommandBox" as CB UI_COLOR
participant ":CommandHistory" as CH UI_COLOR

User -> CB : type "add Alice" + press Enter
CB -> CH : add("add Alice")
CH -> CH : reset()
CH --> CB : (returns true)
CB -> CB : clear input (commandTextField.setText(""))

@enduml
